#pragma once
int split_color();
int change_color();
int detect_color();
int detect_circle();
int find_contour();
int find_particle(void);
int blur_detect();
int canny_edge_detector();
int detect_blob();
int edge();
int autofocus();
int draw_rgb();